precommit:
	go mod tidy
	go fmt ./...
	go build ./...

# CGO is disabled to match release builds; on recent macOS, cgo-linked test
# binaries built with older Go toolchains are killed for missing LC_UUID.
test:
	CGO_ENABLED=0 go test ./...
